# Generated by Django 5.2.1 on 2025-05-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_levelchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='levelchangerequest',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
